name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: # macos-latest -> arm64, macos-13 -> x64
        #os: [windows-latest, ubuntu-latest, macos-latest, macos-13]
        os: [windows-latest, macos-13, macos-latest, ubuntu-latest]
        # < 16 not available in testing images
        #node-version: [22, 20, 18, 16]
        node-version: [22]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies and test
        shell: bash
        run: |
          npm install
          npm test
      - name: build with node-gyp
        shell: bash
        run: |
          npm install -g node-gyp
          which node || true
          whereis node || true
          # node-gyp configure --node-dir=$(which node)
          echo "node-gyp build"
          node-gyp build --node-dir=$(which node)
          echo "node-gyp rebuild"
          node-gyp rebuild --node-dir=$(which node)
      - name: prebuild
        shell: bash
        run: |
          npm run prebuild
      - uses: actions/upload-artifact@v4
        with:
          name: prebuilds
          path: prebuilds/ # or path/to/artifact


